# Generated by Django 4.1.1 on 2022-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221221_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
